pytest-dev/pytest-timeout

- README.rst
The integer requirement was apparently removed in version 1.2.0, but the README does not reflect the change.
> README.rst: The timeout is not limited to integers

- README.rst
https://github.com/pytest-dev/pytest/issues/2993
Not making a fuss, just one of two things I noticed reading the readme.
> It's pytest not py.test

- .pre-commit-config.yaml
- README.rst
- pytest_timeout.py
- setup.py
- test_pytest_timeout.py
- tox.ini
Fixes #32 
~~This improved functionality is implemented by checking if `pydevd.py` appears in any of the stack frames. If it does, we assume that a debugging session is active.~~ See discussion for evolution of detection.
Also updated:
- `py.test` -> `pytest`, `py.test` is apparently deprecated
- `README.rst` to reflect new functionality
> Disable timing-out when a debugging session is in progress

- .github/workflows/main.yml
- README.rst
- pytest_timeout.py
- test_pytest_timeout.py
* Added a pre-release run to CI: this helps testing pytest-timeout with pytest prereleases from now on.
* Fix compatibility with pytest prereleases: the problem was that StrictVersion from distutils doesn't recognize a release candidate (such as 6.0.0rc1) as a valid version, although it is supported by [PEP-0440](https://www.python.org/dev/peps/pep-0440/#pre-releases).
* Fix `is_debugging` function: it was using `name in <module object>` which is a TypeError. It was working previously with the builtin pdb because of the pytest_enter_pdb hook which is triggered by pytest.
Fix #68
> Fix compatibility with pytest pre-releases

- test_pytest_timeout.py
Skip test_cov gracefully if pytest_cov module can't be imported.
This would help us since we're removing py2 support from pytest-cov
but still need it for pytest-timeout.
> Skip test_cov if pytest-cov is not installed

- tox.ini
You get a much nicer UX when a test fails. It can't hurt to use this.
> Annotate test failures in CI

- .gitignore
- README.rst
- pytest_timeout.py
- test_pytest_timeout.py
This method times-out the thread on windows without crashing the test worker.
> switch to thread timeout method when not on main-thread

- README.rst
- pytest_timeout.py
- setup.py
Fixes #91
I tried to test with pytest 4.x, but the tests fail because of an API change in attrs (which pytest depends on). 
I've instead opted for 5.0.0 (released June 2019) as the lower bound.
> Increase pytest requirment to >=5.0.0

- README.rst
Changes:
1. Python and configuation is highlighted
2. Backquotes are fixed where needed
> Improves code highlighting

- pytest_timeout.py
Fixes #78 
It seems like PyCharm changed the module they use (or at least the name).
> Fixed PyCharm debugger timeouts

- setup.py
Note: supporting python_requires requires setuptools>=24.2.0 and pip>=9.0.0 to benefit from it.
Details here: https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires
Will prevent users with Python 2.7 or 3.5 from downloading a sdist version they cannot build.
I see two problems: 
- seems like you dropped the Python 2 support by adding https://github.com/pytest-dev/pytest-timeout/blob/master/setup.py#L4. If you will try to build this on python 2 you will get this error: `'encoding' is an invalid keyword argument for this function`
- The pytest version has been upgraded to the latest from what I can see in the setup.py https://github.com/pytest-dev/pytest-timeout/blob/master/setup.py#L19 and starting from the 5.0.0 version, pytest dropped the Python 2 …
> fix: add setuptools python_requires check

- .pre-commit-config.yaml
- README.rst
https://github.blog/2021-09-01-improving-git-protocol-security-github/
> Github removed the git protocol

- pytest_timeout.py
Previously, the debugger was only recognized if the name was matching exactly one of the well-known debugger names, which was not working as expected on MacOS. With these changes, a debugger that is called `pydevd_frame_evalaluator_darwin_39_64` would also be recognized by the prefix `pydevd_frame_evaluator`, thus disabling timeouts.
See: #109
> Making detection of whether a debugger is attached more flexible

- pytest_timeout.py
> Replace deprecated py.io.get_terminal_width() with shutil.get_terminal_size()

- README.rst
- pytest_timeout.py
- test_pytest_timeout.py
Using bare `pytest-timeout` with `pytest-asyncio` works but timeout's traceback is not perfect.
It points at `selector.select()` call (`epoll.poll()` for linux case for example) instead of timed out `await f(...)` call.
`pytest-asyncio` has a pull request for providing better timeout support https://github.com/pytest-dev/pytest-asyncio/pull/216 which generates awesome tracebacks but doesn't work well with a debugger.
I don't want to copy-paste all hard work that is done by `pytest-timeout` already but propose two hooks instead: `pytest_timeout_setup(item)` and `pytest_timeout_teardown(item)`, both are marked as `tryfirst=True`.
Having these hooks, `pytest-asyncio` can provide its own implementation (which should use `pluginmanager.get_plugin('timeout').is_debugging()`, sure) to override …
> Add custom hooks specifications for overriding setup_timeout and teardown_timeout methods

- pytest_timeout.py
- test_pytest_timeout.py
A simple change to ensure that if func_only is not specified on a timeout marker, it can utilize the environment default. Presently when this function is called as part of `_get_item_settings` it returns False, so it never enters the following check to utilize the environment default:
```
if func_only is None:
func_only = item.config._env_timeout_func_only
```
This change should not impact the usage in `get_env_settings` since that function converts it to a boolean via `return Settings(timeout, method, func_only or False)`.
The motivation is that we were seeing tests fail in fixtures due to timeouts when the default in pytest.ini was set to `timeout_func_only = true`. The only present workaround is to explicitly specify the func_only argument to every instance of a timeout marker on …
> Func Only Respects Environment Default

- pytest_timeout.py
...by setting default on config file parsing level.
pytest itself will validate that the value is a valid boolean,
and if it is not set it will supply default `False` value.
We later rely on this global default being always set and correct -
falling back to it on test level.
This improves upon #122
> Simplify handling of `func_only`

- README.rst
- pytest_timeout.py
- test_pytest_timeout.py
Useful when running tests in a GitHub Action that executes every time you push.
Also added a marker/ini option for other use cases.
Example Usage:
`pytest --timeout=3 --timeout-disable-debugger-detection`
> add `--timeout-disable-debugger-detection` flag

- pyproject.toml
- setup.cfg
- setup.py
This enables building/installing without using deprecated setup.py (but setup.py is still available).
> Add a pyproject.toml and setup.cfg

- pytest_timeout.py
When `trace_func` comes from cython module, `inspect.getmodule` returns `None`. Fallback to getting module from `__class__` of `trace_func`.
Closes #146
> Fix is_debugging for pydevd with cython (#146)

- README.rst
Related to https://github.com/pytest-dev/pytest-timeout/issues/142#issuecomment-1753528786
> docs: add a warning about using `timeout_func_only = true` in INI alongside with `pytest.mark` on a test

- .pre-commit-config.yaml
- README.rst
- pytest_timeout.py
- setup.cfg
- test_pytest_timeout.py
- tox.ini
Additionally update pre-commit hook versions
> Switch to Pytest's terminal reporter

- .gitignore
- README.rst
- pytest_timeout.py
- test_pytest_timeout.py
> add --session-timeout

- README.rst
In `pytest-xdist 3.0`, the option `--boxed` was removed in favor of the `pytest-forked` plugin.
This PR adjusts the advice in the README file to the new (well... Dec 2021) situation.
> Update README.rst with pytest-xdist 3.0.2 news

- pytest_timeout.py
- test_pytest_timeout.py
Is should have less than 60 chars for most timeout values and is more direct than the one I proposed in the issue.
Closes #179
> Change error message to clearly relate it to pytest-timeout
